# Generated by Django 2.2.4 on 2019-08-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
